import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { MetricPoint, RealtimeMetricsResponse } from '../../../core/models/api.models';

@Component({
  selector: 'app-realtime-metrics',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section class="card" *ngIf="metrics; else emptyState">
      <h3 class="section-title">Metricas en tiempo real</h3>

      <div class="grid">
        <article class="metric" *ngFor="let key of chartKeys">
          <header>
            <strong>{{ key | titlecase }}</strong>
            <small>A/B: {{ latestValue(key, 'a') }} / {{ latestValue(key, 'b') }}</small>
          </header>

          <svg viewBox="0 0 220 110" role="img" [attr.aria-label]="'Grafica de ' + key">
            <g class="axis-grid">
              <line x1="32" y1="16" x2="32" y2="90"></line>
              <line x1="32" y1="90" x2="208" y2="90"></line>
              <line x1="32" y1="53" x2="208" y2="53"></line>
            </g>

            <text x="26" y="92" class="axis-label" text-anchor="end">0</text>
            <text x="26" y="56" class="axis-label" text-anchor="end">{{ maxValue(key) / 2 | number:'1.0-0' }}</text>
            <text x="26" y="18" class="axis-label" text-anchor="end">{{ maxValue(key) | number:'1.0-0' }}</text>

            <polyline [attr.points]="toPolyline(getSeries(key, 'a'))" class="line-a"></polyline>
            <polyline [attr.points]="toPolyline(getSeries(key, 'b'))" class="line-b"></polyline>
          </svg>

          <p class="legend">
            <span class="dot a"></span><span>Agente A</span>
            <span class="dot b"></span><span>Agente B</span>
          </p>
        </article>
      </div>
    </section>

    <ng-template #emptyState>
      <section class="card">
        <h3 class="section-title">Metricas en tiempo real</h3>
        <p class="muted">Las series se llenaran cuando empiece la partida.</p>
      </section>
    </ng-template>
  `,
  styles: [`.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:1rem}.metric{border:1px solid #d8dde7;border-radius:.7rem;padding:.85rem;background:#fff;display:grid;gap:.55rem}header{display:flex;justify-content:space-between;gap:.5rem;align-items:center}strong{font-size:.88rem;color:#2d3547}small{font-family:var(--font-mono);color:#5f6878;font-size:.76rem}svg{width:100%;height:140px;background:#fff;border:1px solid #d8dde7;border-radius:.5rem}.axis-grid line{stroke:#e7ebf3;stroke-width:1}.axis-label{fill:#6d7688;font-size:7px;font-family:var(--font-mono)}.line-a{fill:none;stroke:#1d6fa5;stroke-width:2}.line-b{fill:none;stroke:#dd6b20;stroke-width:2}.legend{margin:0;display:flex;align-items:center;gap:.35rem;color:#5f6878;font-size:.72rem}.dot{width:8px;height:8px;border-radius:50%;display:inline-block}.dot.a{background:#1d6fa5}.dot.b{background:#dd6b20}.muted{color:var(--ink-soft);font-size:.9rem}`]
})
export class RealtimeMetricsComponent {
  @Input() metrics: RealtimeMetricsResponse | null = null;

  readonly chartKeys = ['time_ms', 'nodes_expanded', 'eval_calls', 'max_depth'];

  getSeries(key: string, side: 'a' | 'b'): MetricPoint[] {
    if (!this.metrics?.realtime_charts[key]) {
      return [];
    }
    return side === 'a'
      ? this.metrics.realtime_charts[key].series_a
      : this.metrics.realtime_charts[key].series_b;
  }

  latestValue(key: string, side: 'a' | 'b'): string {
    const series = this.getSeries(key, side);
    const last = series.at(-1);
    return last ? `${Math.round(last.value * 100) / 100}` : '-';
  }

  // Generated by GitHub Copilot
  /**
   * Retorna el máximo valor observado entre ambas series para escalar ejes.
   */
  maxValue(key: string): number {
    const values = [
      ...this.getSeries(key, 'a').map(point => point.value),
      ...this.getSeries(key, 'b').map(point => point.value),
    ];

    return Math.max(1, ...values);
  }

  toPolyline(series: MetricPoint[]): string {
    if (!series.length) {
      return '';
    }

    const windowed = series.slice(-20);
    const values = windowed.map(p => p.value);
    const max = Math.max(...values, 1);

    return windowed
      .map((p, idx) => {
        const x = 32 + (idx / Math.max(windowed.length - 1, 1)) * 176;
        const y = 90 - (p.value / max) * 74;
        return `${x},${y}`;
      })
      .join(' ');
  }
}
