import { CommonModule } from '@angular/common';
import { Component, Input, OnChanges, OnInit, SimpleChanges, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { SummaryMetricsResponse } from '../../core/models/api.models';
import { ApiService } from '../../core/services/api.service';

type NumericRecord = Record<string, number | undefined>;

interface SummaryPoint {
  turn: number;
  value: number;
}

interface CostComparisonChart {
  description: string;
  metrics: string[];
  strategy_a: NumericRecord;
  strategy_b: NumericRecord;
}

interface CumulativeChart {
  description: string;
  series_a: SummaryPoint[];
  series_b: SummaryPoint[];
}

interface DepthDistributionChart {
  description: string;
  strategy_a: NumericRecord;
  strategy_b: NumericRecord;
}

interface RadarChart {
  description: string;
  axes: string[];
  strategy_a: NumericRecord;
  strategy_b: NumericRecord;
}

interface PipBalanceChart {
  description: string;
  strategy_a: number;
  strategy_b: number;
}

@Component({
  selector: 'app-metrics-summary',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './metrics-summary.component.html',
  styleUrl: './metrics-summary.component.scss'
})
export class MetricsSummaryComponent implements OnChanges, OnInit {
  private readonly lineWidth = 320;
  private readonly lineHeight = 200;
  private readonly linePadLeft = 42;
  private readonly linePadRight = 14;
  private readonly linePadTop = 14;
  private readonly linePadBottom = 30;

  private readonly api = inject(ApiService);
  private readonly route = inject(ActivatedRoute);

  @Input() sessionId = '';
  @Input() embedded = false;

  loading = false;
  error = '';
  summary: SummaryMetricsResponse | null = null;
  costComparison: CostComparisonChart | null = null;
  cumulativeTime: CumulativeChart | null = null;
  cumulativeNodes: CumulativeChart | null = null;
  depthDistribution: DepthDistributionChart | null = null;
  radar: RadarChart | null = null;
  pipBalance: PipBalanceChart | null = null;
  depthBins: string[] = [];

  // Generated by GitHub Copilot
  /**
   * Carga inicial del resumen cuando el componente se usa como vista de ruta.
   */
  ngOnInit(): void {
    if (this.sessionId) {
      void this.loadSummary(this.sessionId);
      return;
    }

    const idFromRoute = this.route.snapshot.paramMap.get('id');
    if (idFromRoute) {
      this.sessionId = idFromRoute;
      void this.loadSummary(this.sessionId);
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['sessionId']?.currentValue && changes['sessionId'].currentValue !== changes['sessionId'].previousValue) {
      void this.loadSummary(changes['sessionId'].currentValue as string);
    }
  }

  async loadSummary(id: string): Promise<void> {
    this.loading = true;
    this.error = '';

    try {
      this.summary = await firstValueFrom(this.api.getSummaryMetrics(id));
      this.hydrateCharts();
    } catch (error) {
      this.error = error instanceof Error ? error.message : 'No se pudo cargar el resumen.';
      this.resetCharts();
    } finally {
      this.loading = false;
    }
  }

  // Generated by GitHub Copilot
  /**
   * Convierte el payload sin tipar de endgame_charts en estructuras listas para visualización.
   */
  private hydrateCharts(): void {
    const charts = this.asObject(this.summary?.endgame_charts);
    this.costComparison = this.toCostComparison(charts?.['cost_comparison']);
    this.cumulativeTime = this.toCumulative(charts?.['cumulative_time_ms']);
    this.cumulativeNodes = this.toCumulative(charts?.['cumulative_nodes']);
    this.depthDistribution = this.toDepthDistribution(charts?.['depth_distribution']);
    this.radar = this.toRadar(charts?.['radar']);
    this.pipBalance = this.toPipBalance(charts?.['pip_balance']);
    this.depthBins = this.collectDepthBins();
  }

  /**
   * Limpia modelos de gráficos cuando falla la carga o no hay datos.
   */
  private resetCharts(): void {
    this.costComparison = null;
    this.cumulativeTime = null;
    this.cumulativeNodes = null;
    this.depthDistribution = null;
    this.radar = null;
    this.pipBalance = null;
    this.depthBins = [];
  }

  /**
   * Retorna el mayor valor para normalizar alturas en gráficas de barras.
   */
  maxBarValue(valuesA: number[], valuesB: number[]): number {
    return Math.max(1, ...valuesA, ...valuesB);
  }

  /**
   * Convierte un valor a porcentaje de alto relativo para CSS.
   */
  toPercent(value: number, maxValue: number): number {
    if (maxValue <= 0) {
      return 0;
    }
    return (value / maxValue) * 100;
  }

  /**
   * Construye puntos SVG para dos series temporales comparativas.
   */
  toLinePoints(series: SummaryPoint[], maxTurn: number, maxValue: number): string {
    if (!series.length || maxTurn <= 0 || maxValue <= 0) {
      return '';
    }

    return series
      .map(point => {
        const x = this.lineX(point.turn, maxTurn);
        const y = this.lineY(point.value, maxValue);
        return `${x.toFixed(2)},${y.toFixed(2)}`;
      })
      .join(' ');
  }

  // Generated by GitHub Copilot
  /**
   * Calcula la coordenada X para un turno en el área de trazado de la línea.
   */
  lineX(turn: number, maxTurn: number): number {
    const usableWidth = this.lineWidth - this.linePadLeft - this.linePadRight;
    return this.linePadLeft + ((turn - 1) / Math.max(1, maxTurn - 1)) * usableWidth;
  }

  // Generated by GitHub Copilot
  /**
   * Calcula la coordenada Y para un valor usando escala lineal y margen para ejes.
   */
  lineY(value: number, maxValue: number): number {
    const usableHeight = this.lineHeight - this.linePadTop - this.linePadBottom;
    return this.lineHeight - this.linePadBottom - (value / Math.max(1, maxValue)) * usableHeight;
  }

  // Generated by GitHub Copilot
  /**
   * Genera marcas uniformes para el eje X en turnos.
   */
  lineXTicks(maxTurn: number): number[] {
    if (maxTurn <= 1) {
      return [1];
    }
    const steps = Math.min(5, maxTurn);
    const ticks = new Set<number>([1, maxTurn]);
    for (let i = 1; i < steps - 1; i += 1) {
      ticks.add(Math.max(1, Math.round((i / (steps - 1)) * maxTurn)));
    }
    return [...ticks].sort((a, b) => a - b);
  }

  // Generated by GitHub Copilot
  /**
   * Genera marcas uniformes para el eje Y, incluyendo cero y máximo.
   */
  lineYTicks(maxValue: number): number[] {
    const safeMax = Math.max(1, maxValue);
    const steps = 4;
    return Array.from({ length: steps + 1 }, (_, index) => (safeMax / steps) * (steps - index));
  }

  // Generated by GitHub Copilot
  /**
   * Formatea valores de eje para mejorar legibilidad en gráficas densas.
   */
  formatAxisValue(value: number): string {
    if (value >= 1000) {
      return `${(value / 1000).toFixed(1)}k`;
    }
    return `${Math.round(value)}`;
  }

  /**
   * Retorna el turno máximo presente en ambas series.
   */
  maxTurn(seriesA: SummaryPoint[], seriesB: SummaryPoint[]): number {
    return Math.max(1, ...seriesA.map(s => s.turn), ...seriesB.map(s => s.turn));
  }

  /**
   * Retorna el valor máximo presente en ambas series.
   */
  maxSeriesValue(seriesA: SummaryPoint[], seriesB: SummaryPoint[]): number {
    return Math.max(1, ...seriesA.map(s => s.value), ...seriesB.map(s => s.value));
  }

  /**
   * Etiqueta amigable para métricas técnicas.
   */
  formatMetricLabel(metric: string): string {
    return metric.replaceAll('_', ' ');
  }

  /**
   * Valor de profundidad para una estrategia en un bin determinado.
   */
  depthValue(strategy: 'a' | 'b', bin: string): number {
    if (!this.depthDistribution) {
      return 0;
    }
    return strategy === 'a'
      ? (this.depthDistribution.strategy_a[bin] ?? 0)
      : (this.depthDistribution.strategy_b[bin] ?? 0);
  }

  /**
   * Máximo bin de frecuencia para normalizar barras de histograma.
   */
  maxDepthValue(): number {
    if (!this.depthDistribution) {
      return 1;
    }
    const valuesA = Object.values(this.depthDistribution.strategy_a).filter((v): v is number => typeof v === 'number');
    const valuesB = Object.values(this.depthDistribution.strategy_b).filter((v): v is number => typeof v === 'number');
    return Math.max(
      1,
      ...valuesA,
      ...valuesB
    );
  }

  /**
   * Crea coordenadas para el polígono radar normalizado por eje.
   */
  radarPoints(strategy: 'a' | 'b'): string {
    if (!this.radar || this.radar.axes.length === 0) {
      return '';
    }

    const axes = this.radar.axes;
    const centerX = 120;
    const centerY = 120;
    const radius = 90;

    return axes
      .map((axis, index) => {
        const valueA = this.radar?.strategy_a[axis] ?? 0;
        const valueB = this.radar?.strategy_b[axis] ?? 0;
        const axisMax = Math.max(1, valueA, valueB);
        const value = strategy === 'a' ? valueA : valueB;
        const ratio = value / axisMax;
        const angle = (-Math.PI / 2) + (2 * Math.PI * index) / axes.length;
        const x = centerX + Math.cos(angle) * radius * ratio;
        const y = centerY + Math.sin(angle) * radius * ratio;
        return `${x.toFixed(2)},${y.toFixed(2)}`;
      })
      .join(' ');
  }

  /**
   * Retorna las coordenadas de los ejes y etiquetas del radar.
   */
  radarAxes(): Array<{ axis: string; x: number; y: number; lx: number; ly: number }> {
    if (!this.radar || this.radar.axes.length === 0) {
      return [];
    }
    const centerX = 120;
    const centerY = 120;
    const radius = 90;
    return this.radar.axes.map((axis, index) => {
      const angle = (-Math.PI / 2) + (2 * Math.PI * index) / this.radar!.axes.length;
      const x = centerX + Math.cos(angle) * radius;
      const y = centerY + Math.sin(angle) * radius;
      const lx = centerX + Math.cos(angle) * (radius + 16);
      const ly = centerY + Math.sin(angle) * (radius + 16);
      return { axis, x, y, lx, ly };
    });
  }

  /**
   * Devuelve valor de pips para barra horizontal comparativa.
   */
  pipValue(strategy: 'a' | 'b'): number {
    if (!this.pipBalance) {
      return 0;
    }
    return strategy === 'a' ? this.pipBalance.strategy_a : this.pipBalance.strategy_b;
  }

  /**
   * Convierte unknown a objeto plano utilizable.
   */
  private asObject(value: unknown): Record<string, unknown> | null {
    if (!value || typeof value !== 'object') {
      return null;
    }
    return value as Record<string, unknown>;
  }

  /**
   * Convierte unknown a diccionario numérico filtrando valores inválidos.
   */
  private toNumberRecord(value: unknown): NumericRecord {
    const obj = this.asObject(value);
    if (!obj) {
      return {};
    }
    const out: NumericRecord = {};
    for (const [key, val] of Object.entries(obj)) {
      if (typeof val === 'number' && Number.isFinite(val)) {
        out[key] = val;
      }
    }
    return out;
  }

  /**
   * Convierte unknown a lista de puntos turn/value.
   */
  private toSeries(value: unknown): SummaryPoint[] {
    if (!Array.isArray(value)) {
      return [];
    }
    return value
      .map(item => this.asObject(item))
      .filter((item): item is Record<string, unknown> => !!item)
      .map(item => ({ turn: Number(item['turn']), value: Number(item['value']) }))
      .filter(point => Number.isFinite(point.turn) && Number.isFinite(point.value));
  }

  /**
   * Mapea payload de comparación de costos.
   */
  private toCostComparison(value: unknown): CostComparisonChart | null {
    const obj = this.asObject(value);
    if (!obj) {
      return null;
    }
    return {
      description: String(obj['description'] ?? ''),
      metrics: Array.isArray(obj['metrics']) ? obj['metrics'].map(v => String(v)) : [],
      strategy_a: this.toNumberRecord(obj['strategy_a']),
      strategy_b: this.toNumberRecord(obj['strategy_b']),
    };
  }

  /**
   * Mapea payload de series acumuladas.
   */
  private toCumulative(value: unknown): CumulativeChart | null {
    const obj = this.asObject(value);
    if (!obj) {
      return null;
    }
    return {
      description: String(obj['description'] ?? ''),
      series_a: this.toSeries(obj['series_a']),
      series_b: this.toSeries(obj['series_b']),
    };
  }

  /**
   * Mapea payload de histograma de profundidades.
   */
  private toDepthDistribution(value: unknown): DepthDistributionChart | null {
    const obj = this.asObject(value);
    if (!obj) {
      return null;
    }
    return {
      description: String(obj['description'] ?? ''),
      strategy_a: this.toNumberRecord(obj['strategy_a']),
      strategy_b: this.toNumberRecord(obj['strategy_b']),
    };
  }

  /**
   * Mapea payload de radar comparativo.
   */
  private toRadar(value: unknown): RadarChart | null {
    const obj = this.asObject(value);
    if (!obj) {
      return null;
    }
    return {
      description: String(obj['description'] ?? ''),
      axes: Array.isArray(obj['axes']) ? obj['axes'].map(v => String(v)) : [],
      strategy_a: this.toNumberRecord(obj['strategy_a']),
      strategy_b: this.toNumberRecord(obj['strategy_b']),
    };
  }

  /**
   * Mapea payload de balance final de pips.
   */
  private toPipBalance(value: unknown): PipBalanceChart | null {
    const obj = this.asObject(value);
    if (!obj) {
      return null;
    }
    return {
      description: String(obj['description'] ?? ''),
      strategy_a: Number(obj['strategy_a'] ?? 0),
      strategy_b: Number(obj['strategy_b'] ?? 0),
    };
  }

  /**
   * Combina y ordena bins de profundidad de ambas estrategias.
   */
  private collectDepthBins(): string[] {
    if (!this.depthDistribution) {
      return [];
    }
    return [...new Set([
      ...Object.keys(this.depthDistribution.strategy_a),
      ...Object.keys(this.depthDistribution.strategy_b),
    ])].sort((a, b) => Number(a) - Number(b));
  }

  /**
   * Retorna el máximo valor para normalizar las barras de pips.
   */
  maxPipBarValue(): number {
    const valA = this.pipValue('a');
    const valB = this.pipValue('b');
    return Math.max(1, valA, valB);
  }

  /**
   * Retorna array de valores numéricos para una estrategia y lista de métricas.
   */
  getMetricValuesForStrategy(metrics: string[], strategy: 'a' | 'b'): number[] {
    if (!this.costComparison) {
      return [];
    }
    const strategyCosts = strategy === 'a' ? this.costComparison.strategy_a : this.costComparison.strategy_b;
    return metrics.map(m => strategyCosts[m] ?? 0);
  }

  /**
   * Retorna el máximo valor para normalizar las barras de costos.
   */
  maxCostBarValue(): number {
    if (!this.costComparison || !this.costComparison.metrics) {
      return 1;
    }
    const valuesA = this.getMetricValuesForStrategy(this.costComparison.metrics, 'a');
    const valuesB = this.getMetricValuesForStrategy(this.costComparison.metrics, 'b');
    return Math.max(1, ...valuesA, ...valuesB);
  }
}
